# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.potato_frame = QtWidgets.QFrame(self.centralwidget)
        self.potato_frame.setGeometry(QtCore.QRect(260, 0, 250, 250))
        self.potato_frame.setStyleSheet("image: url(Photos/Img/potato-png-38705.png);\n"
"border-radius: 20px;")
        self.potato_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.potato_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.potato_frame.setObjectName("potato_frame")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(10, 60, 400, 200))
        self.main_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.318, x2:1, y2:0.471591, stop:0 rgba(211, 215, 207, 255), stop:1 rgba(193, 125, 17, 255));\n"
"border-radius: 20px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.potato_label = QtWidgets.QLabel(self.main_frame)
        self.potato_label.setGeometry(QtCore.QRect(40, 40, 101, 61))
        self.potato_label.setStyleSheet("font: 75 italic 31pt \"Z003\";\n"
"background-color: none;")
        self.potato_label.setObjectName("potato_label")
        self.welcome_label = QtWidgets.QLabel(self.main_frame)
        self.welcome_label.setGeometry(QtCore.QRect(70, 110, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(33)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("font: 75 italic 33pt \"Z003\";\n"
"background-color: none;")
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setObjectName("welcome_label")
        self.loading_label = QtWidgets.QLabel(self.main_frame)
        self.loading_label.setGeometry(QtCore.QRect(10, 180, 161, 17))
        self.loading_label.setStyleSheet("font: 63 italic 11pt \"URW Bookman\";\n"
"background-color: none;")
        self.loading_label.setObjectName("loading_label")
        self.loading_progressBar = QtWidgets.QProgressBar(self.main_frame)
        self.loading_progressBar.setGeometry(QtCore.QRect(150, 170, 221, 23))
        self.loading_progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(233,185,110);\n"
"border-style: none;\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,136,255,255), stop:1 rgba(255,255,255,255));\n"
"border-radius:10px;\n"
"}")
        self.loading_progressBar.setProperty("value", 24)
        self.loading_progressBar.setObjectName("loading_progressBar")
        self.potao_border_frame = QtWidgets.QFrame(self.centralwidget)
        self.potao_border_frame.setGeometry(QtCore.QRect(260, 0, 250, 250))
        self.potao_border_frame.setStyleSheet("border: 5px solid rgb(233, 185, 110); \n"
"border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0.985075, y2:0, stop:0 rgba(193, 125, 17, 194), stop:1 rgba(255, 255, 255, 255));")
        self.potao_border_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.potao_border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.potao_border_frame.setObjectName("potao_border_frame")
        self.potao_border_frame.raise_()
        self.main_frame.raise_()
        self.potato_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.potato_label.setText(_translate("MainWindow", "Potato"))
        self.welcome_label.setText(_translate("MainWindow", "WELCOME"))
        self.loading_label.setText(_translate("MainWindow", "Please wait....."))
# import photo_rc
