# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(209, 200)
        Form.setMinimumSize(QtCore.QSize(200, 200))
        Form.setMaximumSize(QtCore.QSize(209, 200))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(200, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.forward = QtWidgets.QPushButton(self.frame)
        self.forward.setMinimumSize(QtCore.QSize(34, 34))
        self.forward.setMaximumSize(QtCore.QSize(40, 40))
        self.forward.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon/up-arrow-png-27168.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward.setIcon(icon)
        self.forward.setIconSize(QtCore.QSize(34, 34))
        self.forward.setObjectName("forward")
        self.gridLayout_2.addWidget(self.forward, 0, 1, 1, 1)
        self.left = QtWidgets.QPushButton(self.frame)
        self.left.setMinimumSize(QtCore.QSize(34, 34))
        self.left.setMaximumSize(QtCore.QSize(40, 40))
        self.left.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/Icon/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left.setIcon(icon1)
        self.left.setIconSize(QtCore.QSize(34, 34))
        self.left.setObjectName("left")
        self.gridLayout_2.addWidget(self.left, 1, 0, 1, 1)
        self.stop = QtWidgets.QPushButton(self.frame)
        self.stop.setMinimumSize(QtCore.QSize(40, 40))
        self.stop.setMaximumSize(QtCore.QSize(40, 40))
        self.stop.setStyleSheet("background-color: rgb(204, 0, 0);")
        self.stop.setObjectName("stop")
        self.gridLayout_2.addWidget(self.stop, 1, 1, 1, 1)
        self.right = QtWidgets.QPushButton(self.frame)
        self.right.setMinimumSize(QtCore.QSize(34, 34))
        self.right.setMaximumSize(QtCore.QSize(40, 40))
        self.right.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/Icon/right_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right.setIcon(icon2)
        self.right.setIconSize(QtCore.QSize(34, 34))
        self.right.setObjectName("right")
        self.gridLayout_2.addWidget(self.right, 1, 2, 1, 1)
        self.back = QtWidgets.QPushButton(self.frame)
        self.back.setMinimumSize(QtCore.QSize(34, 34))
        self.back.setMaximumSize(QtCore.QSize(40, 40))
        self.back.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/Icon/back_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon3)
        self.back.setIconSize(QtCore.QSize(34, 34))
        self.back.setObjectName("back")
        self.gridLayout_2.addWidget(self.back, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.stop.setText(_translate("Form", "STOP"))
import icons_rc
